import Link from 'next/link';

export default function HomePage() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center p-6 text-center animate-fade-in relative overflow-hidden">
      {/* Decorative background blur elements */}
      <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-razor-accent/20 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-razor-teal/30 rounded-full blur-[120px] pointer-events-none" />
      
      <div className="max-w-4xl mx-auto z-10 animate-slide-up">
        <div className="inline-flex items-center gap-2 bg-razor-teal/40 border border-razor-accent/30 text-razor-green text-sm font-bold px-5 py-2 rounded-full mb-8 shadow-inner backdrop-blur-sm">
          <span>🤖</span> Powered by Google Gemini AI
        </div>
        
        <h1 className="text-5xl md:text-7xl font-black text-white mb-8 leading-[1.1] tracking-tight">
          Ace Your Next<br />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-razor-accent via-razor-green to-razor-peach">
            Tech Interview
          </span>
        </h1>
        
        <p className="text-slate-300 text-lg md:text-xl mb-12 max-w-2xl mx-auto leading-relaxed font-medium">
          Practice with real interview questions, get instant AI feedback, stream hints, and track your progress over time.
        </p>
        
        <div className="flex flex-col sm:flex-row gap-5 justify-center">
          <Link href="/register"
            className="flex items-center justify-center gap-2 bg-razor-peach hover:bg-razor-peach/90 text-razor-navy font-black px-10 py-4 rounded-xl text-lg transition-all duration-300 shadow-lg shadow-razor-peach/20 hover:shadow-razor-peach/40 transform hover:-translate-y-1">
            🚀 Get Started Free
          </Link>
          <Link href="/login"
            className="flex items-center justify-center bg-razor-teal/30 hover:bg-razor-teal/60 border border-razor-accent/30 text-white font-bold px-10 py-4 rounded-xl text-lg transition-all duration-300 backdrop-blur-sm hover:border-razor-accent/50">
            👤 Sign In
          </Link>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-20 text-left">
          {[
            { icon: '🎯', title: 'AI Questions', desc: 'Role-specific technical questions generated by Gemini AI.' },
            { icon: '📈', title: 'Deep Scoring', desc: 'Detailed clarity, technical, and relevance scoring.' },
            { icon: '💡', title: 'Live Hints', desc: 'Streaming AI assistance when you get stuck.' },
          ].map((f, i) => (
            <div key={f.title} className="glass-panel p-8 rounded-2xl hover:border-razor-accent/40 transition-all duration-300 hover:-translate-y-1" style={{ animationDelay: `${i * 100}ms` }}>
              <div className="bg-razor-teal/50 w-14 h-14 rounded-xl flex items-center justify-center text-3xl mb-5 shadow-inner border border-razor-accent/20">
                {f.icon}
              </div>
              <h3 className="text-white font-bold text-xl mb-2">{f.title}</h3>
              <p className="text-slate-300/90 text-sm leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}
