import Link from 'next/link';

export default function HomePage() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-950 to-slate-900 flex flex-col items-center justify-center p-6 text-center">
      <div className="max-w-3xl mx-auto">
        <div className="inline-block bg-purple-500/20 border border-purple-500/30 text-purple-300 text-sm font-semibold px-4 py-2 rounded-full mb-6">
          Powered by Google Gemini AI
        </div>
        <h1 className="text-5xl md:text-6xl font-black text-white mb-6 leading-tight">
          Ace Your Next<br />
          <span className="bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">
            Tech Interview
          </span>
        </h1>
        <p className="text-slate-400 text-xl mb-10 max-w-xl mx-auto leading-relaxed">
          Practice with real interview questions, get instant AI feedback, stream hints, and track your progress over time.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Link href="/register"
            className="bg-purple-600 hover:bg-purple-700 text-white font-bold px-8 py-4 rounded-xl text-lg transition-colors duration-200 shadow-lg shadow-purple-900/50">
            Get Started Free →
          </Link>
          <Link href="/login"
            className="bg-slate-700/50 hover:bg-slate-700 border border-slate-600 text-white font-bold px-8 py-4 rounded-xl text-lg transition-colors duration-200">
            Sign In
          </Link>
        </div>

        <div className="grid grid-cols-3 gap-6 mt-16 text-center">
          {[
            { icon: '🤖', title: 'AI Questions', desc: 'Role-specific questions generated by Gemini' },
            { icon: '📊', title: 'Deep Scoring', desc: 'Clarity, technical, and relevance scores' },
            { icon: '💡', title: 'Live Hints', desc: 'Streaming hints when you get stuck' },
          ].map((f) => (
            <div key={f.title} className="bg-slate-800/40 border border-slate-700 rounded-2xl p-5">
              <div className="text-3xl mb-3">{f.icon}</div>
              <h3 className="text-white font-semibold mb-1">{f.title}</h3>
              <p className="text-slate-400 text-sm">{f.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}
